nuxt/vue-meta

README.md, examples/basic-render/app.js, examples/basic/app.js, examples/vue-router/app.js, examples/vuex-async/App.vue, examples/vuex-async/views/Home.vue, examples/vuex-async/views/Post.vue, examples/vuex/App.vue, examples/vuex/views/Home.vue, examples/vuex/views/Post.vue, src/shared/getComponentOption.js, src/shared/getMetaInfo.js, test/getComponentOption.spec.js
Should resolve #14, but introduces an unavoidable breaking change.
This method is far less error-prone, though.
=> Favor function syntax over per-attribute function syntax

README.md, examples/vuex-async/store.js, examples/vuex-async/views/Post.vue, src/client/batchUpdate.js, src/shared/plugin.js
...and enable automatic updates after asynchronous data changes by making `metaInfo` reactive.
resolves #17
=> circumvent need to call refresh() after async actions

examples/vuex-async/App.vue, examples/webpack.config.babel.js, src/shared/getMetaInfo.js, test/getMetaInfo.spec.js
See Issue #14 when vmid does not exist.
I also updated the loader to make them more explicit, it seems that with the last update of webpack, we have use the exact module name.
=> Fix: merge array if vmid is undefined

src/client/batchUpdate.js
=> batchupdate fallback to setTimeout

README.md, package.json, rollup.config.js
resolves #25
> Given that `jsnext:main` is a non-standard property that won't stick around for long, and `vue-meta` is bundled into one file with no dynamic module internals as well as the fact that if you're using `vue-meta`, you're 99.9% likely to not be using it conditionally - the decision has been made to drop support for it entirely.
=> Drop support for jsnext:main

src/shared/plugin.js
Apparently buble doesn't bother to enforce TDZ (babel side of the story - https://github.com/babel/babel/issues/563). As the result `defaultOptions` is undefined when Vue.use(VueMeta) is called (https://jsfiddle.net/u7p5daps/). Simple reordering fixes the problem.
=> Fix undefined defaultOptions

src/client/updaters/updateTags.js
fixed issue where including metaInfo with the same script across multiple components on the same page includes it multiple times. this will de-dupe any of the same tags so that only one is ever inserted
=> Fixed issue with duplicate insertions

src/shared/plugin.js
=> fix bug where old metadata would persist after returning from a child route to the parent

src/server/inject.js
`titleChunk.text()` will cause error. It should be a plain string.
=> generateServerInjector(): excluding titleChunk

src/shared/plugin.js
This PR fixes a server crash when using this plugin with vue-router-sync. https://github.com/declandewet/vue-meta/issues/82
When using these two plugins with SSR, the server crashes with a "document is not defined" Exception.
This exception is thrown because the `destroyed` method is called when handing the page over from the server to the client.
By not calling the `refresh` method on the server side we can avoid this exception and save render-time by not calling a method that has no effect when executed on the server.
=> do not trigger a client refresh on the server side

src/server/generators/tagGenerator.js
the vue-meta add an attribute to observe it's change.
```
Vue.use(Meta, {
attribute: 'data-vue-meta', // the attribute name vue-meta adds to the tags it observes
})
```
It work in most case, but not all. for example, when I verify a website in baidu.com, I have to add a tag in html's head
```
<meta name="baidu-site-verification" content="xxxxxxxx"/>
```
I add the code like this,
```
meta: [
{name: 'baidu-site-verification', content: 'xxxxxxxx'}
]
```
Unfortunately, the code above will fail to verify, because it generate the html like this
```
<meta data-vue-meta="true" name="baidu-site-verification" content="xxxxxxxx"/>
```
the attribute `data-vue-meta` is **NOT** expect in this verification.
The keyword `once` mean not to observe the tag's change, and not need to generate a redundancy …
=> In some case, we do need a clean tag without any other redundancy attributes. 

src/client/updateClientMetaInfo.js, src/server/generateServerInjector.js, src/server/generators/attrsGenerator.js, src/shared/getMetaInfo.js
https://github.com/declandewet/vue-meta/issues/122
=> added headAttrs

src/shared/plugin.js
In Vue ecosystem, autoinstall feature is dedicated for cases when libraries are being included from CDN, instead of being bundled with the app. But testing for `Vue` being globally available is not enough to correctly target these cases. It also triggers if `Vue` is made globally available e.g. with webpack's `ProvidePlugin`.
Proposed solution avoids this problem. It's also used by [vuex](https://github.com/vuejs/vuex/blob/7d611adcca86d0a34fca3074a96dd958bd94f733/src/store.js#L13) and [vue-router](https://github.com/vuejs/vue-router/blob/05a5f085fd7e230d4b51862f7a6086fec4378bc6/src/util/dom.js#L3).
=> Improve automatic installation criteria

README.md, examples/ssr.tagid.js, src/shared/getMetaInfo.js, test/getMetaInfo.spec.js
Specify which property for which tagIDKeyName should not be sanitized.
See #130 for the rationale
=> Add __dangerouslyDisableSanitizersByTagID property

src/shared/plugin.js
Another occurrence where running `vue-meta` on the server errors. I'm not sure if this is the best place to put it or somewhere else in the stack, but from what I can tell everything still works as expected.
Error:
```
/project/node_modules/vue-meta/lib/vue-meta.js:849
var htmlTag = document.getElementsByTagName('html')[0];
^
ReferenceError: document is not defined
at Vue$3.updateClientMetaInfo (/project/node_modules/vue-meta/lib/vue-meta.js:849:56)
at Vue$3.refresh (/project/node_modules/vue-meta/lib/vue-meta.js:918:36)
at /project/node_modules/vue-meta/lib/vue-meta.js:1036:78
at Timeout._onTimeout (/project/node_modules/vue-meta/lib/vue-meta.js:957:5)
at ontimeout (timers.js:386:11)
at tryOnTimeout (timers.js:250:5)
at Timer.listOnTimeout (timers.js:214:5)
```
Current setup:
app.js …
=> Fix document is not defined error with SSR

README.md, src/shared/constants.js, src/shared/getComponentOption.js, src/shared/getMetaInfo.js, src/shared/plugin.js, test/getMetaInfo.spec.js
Add meta templates through an extra `template` key in distinct meta objects:
```js
{
metaInfo: {
meta: [
{ charset: 'utf-8' },
{
'vmid': 'og:title',
'property': 'og:title',
'content': 'Test title',
'template': chunk => `${chunk} - My page` //or as string template: '%s - My page'
}
]
}
}
```
will now resolve to
```
<meta charset="utf-8">
<meta name="og:title" property="og:title" content="Test title - My page">
```
Related: #112, #141 (a little)
=> Add meta templates

package-lock.json, src/shared/constants.js, src/shared/getComponentOption.js, src/shared/getMetaInfo.js, src/shared/plugin.js, test/getMetaInfo.spec.js
Addresses issues left over in #202, especially that templates in the parent component are applied with child values.
Scenarios:
=> [WIP] feat: better template support

src/shared/getComponentOption.js, src/shared/plugin.js, test/getComponentOption.spec.js, test/getMetaInfo.spec.js, test/plugin.spec.js
=> feat: merge mixins options

README.md
I started getting an error saying "All declarations of metaInfo must have identical modifiers" after updating to the stable version of vue-cli. After some investigation, it looks like the code in this snippet is causing conflicts with the typings that have since been added to the actual code. Removing the code snippet removed the error, and the type hints still work properly.
Hope this helps!
=> Removed old Typescript snippet from README

src/shared/getComponentOption.js, src/shared/plugin.js, test/getComponentOption.spec.js, test/getMetaInfo.spec.js, test/plugin.spec.js
This reverts commit ad4d61c.
Sorry for the problems and inconveniences caused!
Resolves #269 https://github.com/nuxt-community/nuxt-i18n/issues/127 https://github.com/nuxt/nuxt.js/issues/3957
=> Revert "feat: merge mixins options"

src/server/generators/tagGenerator.js, yarn.lock
Noticed that sometimes I get an empty object sent here and it makes the vue-meta print out empty tags with no value what so ever. Maybe there is a reason why there is no check for an empty object. I know there should not be empty objects sent here but if something does, it will at least not print empty tags. :) 
Let me know if this a good or bad idea.
=> Bail on empty objects sent to the tagGenerator function

package.json
The `yarn.lock` file which is included in npm packages has `220K` overhead which is ignored by yarn according to the [docs](https://yarnpkg.com/lang/en/docs/yarn-lock/#toc-current-package-only)
=> fix(pkg): remove extra yarn.lock from npm package

README.md
Fixes https://github.com/declandewet/vue-meta/issues/303
=> doc: add tips about inline script in README.md `script` example

types/index.d.ts
`innerHTML` should be optional
=> Fix type annotation for script tag

.travis.yml, src/server/generators/tagGenerator.js
While I was looking at the changes done by the html-minifier when generating my (Nuxt) project, I noticed that vue-meta doesnt strictly follow the html specifications. Both `base`, `link` as `meta` tags dont need to have an endtag. See: https://www.w3.org/TR/html52/document-metadata.html
Fixes: #270
=> fix: follow html specs with regards to end tags

types/vue.d.ts
Updated Vue method to $meta
Resolves #242
=> fix: $meta is not defined in Vue interface type (#242)

src/server/generators/titleGenerator.js
Fix https://github.com/nuxt/nuxt.js/issues/5281
=> fix: don't generate title tag if title is empty

src/server/generators/tagGenerator.js
its not supported in IE and not polyfilled in vue-meta v1
Before releasing v1.6 we need to fix a previous pr by me as v1 doesnt get polyfilled and we still want to support IE.
=> refactor: dont use includes

.circleci/config.yml, examples/index.html, examples/multiple-apps/app.js, examples/multiple-apps/index.html, examples/package.json, examples/ssr/app.js, src/client/$meta.js, src/client/refresh.js, src/client/updateClientMetaInfo.js, src/client/updaters/tag.js, src/server/$meta.js, src/server/generateServerInjector.js, src/server/generators/tag.js, src/server/generators/title.js, src/server/inject.js, src/shared/constants.js, src/shared/mixin.js, test/unit/components.test.js, test/unit/generators.test.js, test/unit/plugin-browser.test.js, test/unit/plugin-server.test.js, test/unit/updaters.test.js, test/utils/index.js, test/utils/meta-info-data.js
Resolves: #372 
Problems with this implementation:
- have no good solution found yet for html, head, body attributes
- although vmid's work across app's, support is only partial
- the value of the last refreshed app is used
- given app1 and app2 where app2 removes its value for _vmid1_, then there is no way to retrieve app1's value for _vmid1_ which means the element is removed
The new multi app example renders as follows:
=> feat: support multiple apps on one page

types/vue-meta.d.ts
This PR adds support for schema.org meta tags, like the following ones:
```html
<html>
...
<meta itemprop="@type" content="Event">
<meta itemprop="datePublished" content="2019-06-07">
...
</html>
```
=> feat(ts): add microdata meta tag type

src/shared/mixin.js
If `...$el` is a comment node (which appears to happen during initialization under some circumstances), it will be truthy but won't have `hasAttribute`.
=> fix: ensure hasAttribute exists on $root.$el

src/server/generators/title.js, src/shared/escaping.js, src/utils/is-type.js, test/unit/escaping.test.js, test/unit/generators.test.js
Fixes https://github.com/nuxt/nuxt.js/issues/6063
=> fix: don't generate <title> tag if metaInfo.title is falsy

src/client/updaters/tag.js, src/server/generators/tag.js, src/shared/constants.js, src/shared/escaping.js, test/unit/escaping.test.js, test/utils/meta-info-data.js
Resolves: #247 
Quick workaround to circumvent the need for having to disable sanitization for JSON based content in script tags. Just use a json prop instead of innerHTML and the passed value is added by calling JSON.stringify on it. There is no error handling when the supplied json is faulty
=> feat: support json content (without disabling sanitizers)

examples/server.js, examples/ssr/App.js, examples/ssr/browser.js, examples/ssr/server.js, src/client/updaters/tag.js, src/server/generators/tag.js, src/shared/constants.js, src/shared/getComponentOption.js, src/shared/getMetaInfo.js, src/shared/merge.js, src/shared/template.js, test/unit/getMetaInfo.test.js
Both in v1 as in v2 the meta content templates caused wrong content if you would eg run the exact same tests multiple times. This was mainly caused by the fact that templates where removed once used so if both parent and child had templates defined on the second run the other template would be used.
So instead of explicitly removing templates we now keep track if a template has been applied for that specific meta property by setting template to true so a template is never applied twice (this was found in #426).
This fix could potentially break advanced configs like eg chained templates through multiple components though (but not sure if that was even possible, never tried it), but I think its better to support basic functionality as in 426 then advanced configs for now.
=> fix: meta content templates

types/vue-meta.d.ts
According to [MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta#Notes) and [WHATWG](https://html.spec.whatwg.org/multipage/semantics.html#the-meta-element), a `<meta http-equiv>` should contain a `content` attribute and no `name` attribute. The `MetaPropertyEquiv` interface seems wrong about this case and this PR is going to fix the issue.
Closes #435.
=> fix(types): missing property "content" of MetaPropertyEquiv

types/vue-meta.d.ts
The new feature added in #415 does not have a `json` property type definition, so TypeScript compilation fails. This PR adds new interfaces and types.
=> fix(types): missing type for `json` property

types/index.d.ts
To be able to annotate those in user's code when stored individually.
Resolves #440
=> types: export types for meta, link, script interfaces

docs/guide/frameworks.md
Addresses issue #445 - Links to more specific documentation for Nuxt head method.
=> docs: Use direct link to Nuxt documentation

src/shared/getComponentOption.js, src/shared/mixin.js, test/unit/getComponentOptions.test.js
=> fix: still traverse children when metainfo doesnt return object

src/shared/mixin.js, src/utils/array.js, test/unit/utils.test.js
fix: make sure that beforeMount hook to hydrate from ssr is only added once (disclaimer, havent been able to trigger an issue with this manually tough)
Recently there have been some issues due to third party libs adding a global mixin which sets meta information. Since v2.3 that is not the recommended approach anymore (using addApp is). This pr tries to detect if a global mixin adding _keyName_ was used and logs a warning about that
=> feat: try to detect global mixins adding meta info

docs/api/README.md
Adds a missing comma in the code example in the "Add JSON data" API docs.
=> docs: add missing comma in API docs

src/shared/constants.js
According to the AMP specification, documents [need to include](https://amp.dev/documentation/guides-and-tutorials/learn/spec/amp-boilerplate/) a style tag with the boolean attribute `amp-boilerplate` in the `<head>` of the page. At the moment, adding `amp-boilerplate: true` to a style object in `htmlAttrs` outputs `<style amp-boilerplate="true">`, which leads to an AMP validation error. For this reason, `amp-boilerplate` should be added to the 
`booleanHtmlAttributes`, as it has already been done for the attribute `amp`.
=> feat: add amp-boilerplate as boolean attribute (resolves: #530)

examples/ssr/App.js, src/shared/mixin.js
This should resolve #404 and resolve #562 
@kevinmarrec Would this fix be an issue with Vuetify? I know previously we had issues with that because they start new Vueapp's for modals etc. But I would guess that if you use Vuetify with SSR the Vue app that uses Vuetify will be initiated first?
I feel this fix is a bit hacky, but I dont think there is a proper way that vue-meta can currently pass the appId from ssr to the client without introducing a breaking change. This fix should handle like 99+% of the normal use-cases (if Vuetify plays along).
(The reverts are just because I first pushed on master, but then decided it was better to do a PR first)
=> fix: also set ssrAppId for first Vue app when ssrAttribute exists

docs/api/README.md, src/server/generateServerInjector.js, src/server/generators/attribute.js, src/server/generators/tag.js, src/server/inject.js, src/shared/$meta.js, test/unit/components.test.js, test/unit/generators.test.js
See the added docs.
This pr doesnt fix anything, just provides a (possible) cleaner API to integrators.
=> feat: add support for global inject options

types/vue-meta.d.ts
=> Augment MetaInfo with missing titleChunk

docs/guide/README.md, docs/guide/caveats.md, docs/guide/frameworks.md, docs/guide/metainfo.md
List of changes:
- enclose `vue-meta` in back-ticks
- enclose `metaInfo` and `keyName` in backticks
- provide correct link to Factor docs
- fix small typo
=> docs: enhancements

package.json, yarn.lock
**This PR should bring back the lovely** :heavy_check_mark:
It does so by:
* removing duplicates from lockfile
* upgrading vue to 2.6.12 <details><summary><strong>Current test failure</strong></summary>
```bash
Vue packages version mismatch:
- vue@2.6.12 (/home/circleci/project/node_modules/vue/dist/vue.runtime.common.js)
- vue-template-compiler@2.6.11 (/home/circleci/project/node_modules/tib/node_modules/vue-template-compiler/package.json)
This may cause things to work incorrectly. Make sure to use the same version for both.
If you are using vue-loader@>=10.0, simply update vue-template-compiler.
If you are using vue-loader@<10.0 or vueify, re-installing vue-loader/vueify should bump vue-template-compiler to the latest.
at Object.<anonymous> …
```
=> chore(deps): prune package duplicates from lockfile
