README.md, src/client/refresh.js, src/client/updateClientMetaInfo.js, src/client/updaters/updateTagAttributes.js, src/client/updaters/updateTags.js, src/client/updaters/updateTitle.js, src/server/generateServerInjector.js, src/server/generators/attrsGenerator.js, src/server/generators/tagGenerator.js, src/server/generators/titleGenerator.js, src/server/inject.js, src/shared/$meta.js, src/shared/constants.js, src/shared/getMetaInfo.js, src/shared/plugin.js, test/getMetaInfo.spec.js
=> support custom options

README.md, package.json, src/shared/getMetaInfo.js, src/shared/isArray.js, yarn.lock
=> implement sanitization

package.json, src/shared/getMetaInfo.js, yarn.lock
=> use different escape sequence on client side

src/client/updaters/updateTags.js
=> Fix: check correctly the attribute we want to set

src/shared/plugin.js
see more ElemeFE/element#4207 (comment)
=> refresh meta info only computed $metaInfo exists

src/client/updateClientMetaInfo.js, src/server/generateServerInjector.js, src/server/generators/attrsGenerator.js, src/shared/getMetaInfo.js
referring to issue https://github.com/declandewet/vue-meta/issues/122
=> added support for updating head tag attributes

src/shared/getMetaInfo.js, test/getMetaInfo.spec.js
Fixes #109 
Added a test for original templating behaviour as well.
=> Allow `titleTemplate` to take a function

README.md, src/client/updateClientMetaInfo.js, src/client/updaters/updateTags.js, src/server/generators/tagGenerator.js
fix https://github.com/nuxt/nuxt.js/issues/2000
=> feat: append tag into body

README.md, package-lock.json, package.json, types/index.d.ts, types/tsconfig.json, types/vue.d.ts
Added definitions for TypeScript, addressing issue #157.
Please, consider pushing this to npm.
=> Typings for typescript & usage readme

README.md
We have move `vmid` to the end. If not, open graph will not works.
=> Fix Readme about open graph

README.md
=> docs: add option `headAttrs`

src/client/update.js, src/shared/mixin.js, test/unit/components.test.js
Fixes: #376
See title and code comments
=> fix: detect and apply changes before or during initialisation

scripts/rollup.config.js, src/client/refresh.js, src/index.js, src/server/generate.js, src/server/generateServerInjector.js, src/server/generators/tag.js, src/server/inject.js, src/shared/escaping.js, src/shared/getComponentOption.js, src/shared/getMetaInfo.js, test/unit/components.test.js, test/unit/escaping.test.js, test/unit/generators.test.js, test/unit/getComponentOptions.test.js, test/unit/getMetaInfo.test.js, test/unit/plugin-server.test.js, test/utils/meta-info-data.js
Resolves: #398 
@Atinux @manniL This is just as a FYI, have added this due to linked issue and for SPA renderer in Nuxt :)
=> feat: support generating tags directly from metaInfo object

README.md, docs/guide/frameworks.md
Adding the new Factor platform to list of supporting frameworks.
=> Add Factor to frameworks

src/shared/nav-guards.js, test/unit/components.test.js
Resolve #475 
Need disable `features.transitions: false`
=> fix: afterNavigation

docs/api/README.md
=> docs: adds documentation for json option

docs/faq/chaining.md
proerties -> pro**p**erties
fix #489
=> docs: fix properties typo

types/vue-meta.d.ts
=> Add/Fix http-equiv meta

types/vue-meta.d.ts
=> fixed typescript declaration of titleTemplate

docs/api/README.md, docs/faq/performance.md
Scope of changes restricted to docs.
=> fix(docs): Corrected typos in project documentation
